trigger: none

resources:
  pipelines:
  - pipeline: CI_Build
    source: backend-ci
    branch: main

variables:
  azureServiceConnection: DacpacDemo
  environments: dev

stages:
  - ${{ each env in split(variables.environments, ',')}}:
    - stage: Deploy_${{env}}
      displayName: Deploy to ${{env}}
      jobs:
        - deployment: 'Deploy_${{env}}'
          # creates an Azure DevOps environment if it doesn't exist
          # create in advance and add approval gates to it
          environment: '${{env}}'
          pool:
            vmImage: 'ubuntu-latest'
          displayName: 'Deploy to ${{env}} database'
          strategy:
            runOnce:
              deploy:
                steps:
                  - download: CI_Build

                  - task: AzurePowerShell@5
                    displayName: Capture access token for SQL DB from Azure DevOps Service Connection
                    inputs:
                      azureSubscription: ${{ variables.azureServiceConnection }}
                      scriptType: 'InlineScript'
                      azurePowerShellVersion: LatestVersion
                      Inline: |
                        $context = [Microsoft.Azure.Commands.Common.Authentication.Abstractions.AzureRmProfileProvider]::Instance.Profile.DefaultContext
                        $sqlToken = [Microsoft.Azure.Commands.Common.Authentication.AzureSession]::Instance.AuthenticationFactory.Authenticate($context.Account, $context.Environment, $context.Tenant.Id.ToString(), $null, [Microsoft.Azure.Commands.Common.Authentication.ShowDialog]::Never, $null, "https://database.windows.net").AccessToken
                        Write-Host ("##vso[task.setvariable variable=SQLTOKEN;]$sqlToken")                  

                  - task: SqlAzureDacpacDeployment@1
                    displayName: Deploy .dacpac using access token
                    inputs:
                      azureSubscription: ${{ variables.azureServiceConnection }}
                      AuthenticationType: 'connectionString'
                      ConnectionString: 'Data Source=sql-erikej-dacpacdemo-${{env}}-ne.database.windows.net;Initial Catalog=sqldb-erikej-dacpacdemo-${{env}}-ne;Encrypt=true;Connect Timeout=60'
                      deployType: 'DacpacTask'
                      DeploymentAction: 'Publish'
                      DacpacFile: '$(Pipeline.Workspace)/CI_Build/drop/ErikEJ.DacpacDemo.DatabaseBuild.dacpac'
                      AdditionalArguments: '/AccessToken:$(sqlToken)'
                      IpDetectionMethod: 'AutoDetect'
